### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rklec** [StefanFanaru/PokerTime#2]
Neither on GitHub nor https://marketplace.visualstudio.com/items?itemName=StefanFanaru.poker-time you have provided a license. What is your project's license?

This is quite important to know for using the software, and by default the license is proprietary, see https://choosealicense.com/no-permission/#for-users.

See https://choosealicense.com/

**Comment by StefanFanaru** [comment]
Sorry it took more than a year to reply...
I did not monitor this project.
I have added a license, MPL v2
